function [fvec,gvec] = quadrotorloadVectorFields(in1,in2)
%QUADROTORLOADVECTORFIELDS
%    [FVEC,GVEC] = QUADROTORLOADVECTORFIELDS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    09-Nov-2017 11:53:15

JQ = in2(2,:);
dphiL = in1(7,:);
dphiQ = in1(8,:);
dyL = in1(5,:);
dzL = in1(6,:);
g = in2(6,:);
l = in2(5,:);
lQ = in2(3,:);
mL = in2(4,:);
mQ = in2(1,:);
phiL = in1(3,:);
phiQ = in1(4,:);
t2 = dphiL.^2;
t3 = mL+mQ;
t4 = 1.0./t3;
t5 = phiL-phiQ;
t6 = sin(phiL);
t7 = cos(t5);
t8 = t4.*t6.*t7;
t9 = cos(phiL);
fvec = [dyL;dzL;dphiL;dphiQ;-l.*mQ.*t2.*t4.*t6;-g+l.*mQ.*t2.*t4.*t9;-sin(t5)./mQ;0.0];
if nargout > 1
    t10 = 1.0./JQ;
    gvec = reshape([0.0,0.0,0.0,0.0,t8,-t4.*t7.*t9,0.0,-lQ.*t10,0.0,0.0,0.0,0.0,t8,-t4.*t7.*t9,0.0,lQ.*t10],[8,2]);
end
